name: Essentials
version: 1.0.0
main: frostcheat\essentials\Loader
api: 5.3.0
website: https://github.com/FrostCheat
description: Essentials is the essential plugin for Pocketmine-MP servers, providing core features for servers of any size and scale.
author: frostcheat

permissions:
  essentials.command.back:
    default: true
  essentials.command.back.bypass:
    default: op
  essentials.command.broadcast:
    default: op
  essentials.command.clear:
    default: true
  essentials.command.clear.other:
    default: op
  essentials.command.feed:
    default: op
  essentials.command.feed.other:
    default: op
  essentials.command.feed.bypass:
    default: op
  essentials.command.fly:
    default: op
  essentials.command.fly.other:
    default: op
  essentials.command.heal:
    default: op
  essentials.command.heal.other:
    default: op
  essentials.command.heal.bypass:
    default: op
  essentials.command.ping:
    default: true