 # don't touch this
config-version: 1

showCoordinates: true

saveTime: 600

# Admins can view all private messages
tell-log: true

# built-in cooldowns: (in seconds)
heal.cooldown: 300
feed.cooldown: 120
back.cooldown: 60
milk.cooldown: 120

# timeout for teleport request (in seconds)
tpa.timeout: 120

un-registerCommands:
  - "clear"
  - "gamemode"
  - "tell"
  - "msg"
  - "me"
  - "w"