 # don't touch this
config-version: 1

# built-in cooldowns: (in seconds)
heal.cooldown: 300
feed.cooldown: 120
back.cooldown: 60
smite.cooldown: 300
extinguish.cooldown: 180
milk.cooldown: 120

# timeout for teleport request (in seconds)
tpa.timeout: 120